version: "3.1"

services:
    python1:
      build: python1
      container_name: python1
      volumes:
        - ./:/app
      environment:
            - USER=1
      working_dir: /app
      command: sh
      restart: always
      tty: true
      ports:
        - 8819:8889
