FROM python:3.8

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

# RUN pip install image==1.5.33
# RUN pip install imagehash==4.2.0
# RUN pip install opencv-python==4.4.0.46
RUN pip install scrapy
RUN pip install mysql-connector==2.2.9
#pip install python-rocksdb==0.7.0
# RUN pip install redis
# RUN pip install hiredis